name: action
on:
  push:
    branches: [main]
  schedule:
    - cron:  '0 0 * * *'
  pull_request:
jobs:
  shellcheck:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: run shellcheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -s bash
  build_busybox:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: install deps
        run: |
          sudo apt -y install qemu-utils
      - name: make prepare busybox/initrd root.img
        run: |
          make prepare busybox/initrd busybox/root.img
  build_linux:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        linux_version:
          - "5_15_0_43_46"
          - "5_4_0_65_73"
          - "4_18_0_348_7_1_el8_5"
          - "3_10_0_1160_31_1_el7"
          - "2_6_32_754_35_1_el6"
          - "2_6_39"
    steps:
      - uses: actions/checkout@v2
      - name: make LINUX_VERSION=${{ matrix.linux_version }} prepare bzImage
        run: |
          make LINUX_VERSION=${{ matrix.linux_version }} prepare bzImage
