name: action
on:
  push:
    branches: [main]
  pull_request:
jobs:
  build_busybox:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: install deps
        run: |
          sudo apt -y install qemu-utils
      - name: make prepare busybox/initrd root.img
        run: |
          make prepare busybox/initrd busybox/root.img
  build_linux:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        linux_version:
          - "2_6_39"
          - "2_6_32_754_35_1_el6"
          - "3_10_0_1160_31_1_el7"
          - "4_18_0_348_7_1_el8_5"
          - "5_4_0_65_73"
    steps:
      - uses: actions/checkout@v2
      - name: make LINUX_VERSION=${{ matrix.linux_version }} prepare bzImage
        run: |
          make LINUX_VERSION=${{ matrix.linux_version }} prepare bzImage
