name: action
on:
  push:
    branches: [main]
  pull_request:
jobs:
  build_busybox:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: make busybox/initrd
        run: |
          make busybox/initrd
  build_linux:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        linux_version: ["2_6_39", "2_6_32_754_35_1_el6", "3_10_0_1160_31_1_el7", "5_4_0_65_73"]
    steps:
      - uses: actions/checkout@v2
      - name: make LINUX_VERSION=${{ matrix.linux_version }} bzImage
        run: |
          make LINUX_VERSION=${{ matrix.linux_version }} bzImage
